### ISSUE TITLE
scour 0.35 is broken

### ISSUE THREAD

**Issue by oberstet** [scour-project/scour#125]
```
(cpy2711_15) oberstet@thinkpad-t430s:~/scm/crossbario-com$ make publish
scons img
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Scour(["web/static/img/gen/diagrams/big_picture/big_picture.svg"], ["work/diagrams/big_picture/big_picture.svg"])
WARNING: SVG input document uses 11 flow text elements, which won't render on browsers!
scons: *** [web/static/img/gen/diagrams/big_picture/big_picture.svg] AttributeError : Struct instance has no attribute 'ensure_value'
Traceback (most recent call last):
  File "/home/oberstet/cpy2711_15/lib/python2.7/site-packages/scons-2.5.1/SCons/Action.py", line 1054, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/oberstet/cpy2711_15/lib/python2.7/site-packages/taschenmesser/svg.py", line 70, in Scour
    scour.start(options, instream, outstream)
  File "/home/oberstet/cpy2711_15/lib/python2.7/site-packages/scour/scour.py", line 3709, in start
    sizediff), file = options.ensure_value("stdout", sys.stdout))
AttributeError: Struct instance has no attribute 'ensure_value'
scons: building terminated because of errors.
make: *** [img] Fehler 2
```

**Comment by Ede123** [comment]
Well, this is not really a Scour problem (which works fine) but rather the lack of an official API (#119) that third-parties can rely on.

I guess the issue you faced would already have been fixed with d9b369864d04387b366caa9769ffb198e644e503 since you're already calling `generateDefaultOptions()`.
I just pushed 6cf8c2b7d92848f9eddc0d5badf8f1fd75cd178a to be safe, tough. (Now one could also call `start()` with empty options).
