### ISSUE TITLE
Cannot install scour on clean Windows 10 x64

### ISSUE THREAD

**Issue by cafehaine** [scour-project/scour#154]
Here is the log:
```
C:\Users\CaféHaine>pip install scour
Collecting scour
  Downloading scour-0.36.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 59kB/s
Requirement already satisfied: six>=1.9.0 in c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages (from scour)
Installing collected packages: scour
  Running setup.py install for scour ... error
Exception:
Traceback (most recent call last):
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 21: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\caféhaine\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 21: invalid continuation byte

```

**Comment by Ede123** [comment]
Are you sure it's a Scour issue? Can you install other packages using pip?

First hunch: Your install location of Python could be problematic and might be throwing pip off as the character causing the error (0xe9) is "é" in ASCII and coincidentally your Windows username contains this character.

**Comment by cafehaine** [comment]
`pip install six` works fine, so to me it is a problem with utf-8 in the install script of scour
Maybe other packages are affected by this but this seems to be a scour issue.

**Comment by Ede123** [comment]
You're free to believe whatever you want.

To me (and probably everybody else who cares to [investigate a little](https://github.com/pypa/pip/search?q=UnicodeDecodeError&type=Issues)) this is a pip issue and not specific to Scour.

If you want help you should be a little more cooperative in future...
