### ISSUE TITLE
SyntaxError: expecting a boolean flag on SVG 1.1 reference SVG file 

### ISSUE THREAD

**Issue by nthykier** [scour-project/scour#193]
scour on the current master branch fails to process several of the SVG 1.1 reference SVGs. Below is one of these failures:

```
Processing paths-data-20-f.svg
Traceback (most recent call last):
  File "scour.py", line 3, in <module>
    run()
  File "/home/moon/debian/scour/upstream/scour/scour/scour.py", line 3930, in run
    start(options, input, output)
  File "/home/moon/debian/scour/upstream/scour/scour/scour.py", line 3898, in start
    out_string = scourString(in_string, options).encode("UTF-8")
  File "/home/moon/debian/scour/upstream/scour/scour/scour.py", line 3545, in scourString
    cleanPath(elem, options)
  File "/home/moon/debian/scour/upstream/scour/scour/scour.py", line 2066, in cleanPath
    path = svg_parser.parse(oldPathStr)
  File "/home/moon/debian/scour/upstream/scour/scour/svg_regex.py", line 160, in parse
    return self.rule_svg_path(next_val_fn, token)
  File "/home/moon/debian/scour/upstream/scour/scour/svg_regex.py", line 168, in rule_svg_path
    command_group, token = rule(next_val_fn, token)
  File "/home/moon/debian/scour/upstream/scour/scour/svg_regex.py", line 251, in rule_elliptical_arc
    raise SyntaxError("expecting a boolean flag; got %r" % (token,))
SyntaxError: expecting a boolean flag; got ('float', '6')
```

Options used:
```sh
scour --enable-id-stripping --enable-comment-stripping --shorten-ids --indent=none  --no-line-breaks --strip-xml-prolog --remove-descriptive-elements --set-precision=8 --set-c-precision=8 --create-groups --remove-titles --remove-descriptions --remove-metadata
```

Test data is from: https://www.w3.org/Graphics/SVG/Test/20110816/

Note: This seems to be the last "unique" type of crash on the SVG 1.1 reference files.  Hopefully, once we have solved this, #189, and #188, scour will process the SVG 1.1 reference files without crashing.

**Comment by nthykier** [comment]
This test case appears to be a test of [F.6.2 Out-of-range parameters], which (among other) states:

```
Any nonzero value for either of the flags fA or fS is taken to mean the value 1.
```

And the particular test case contains:

```xml
    <!-- out of range large-arc-flag value -->
    <path d="M280,120 h25 a25,25 0 1,0 -25,25 z" fill="lime" stroke="lime"/>
    <path d="M280,120 h25 a25,25 0 6 0 -25,25 z" fill="red"/>
```

In other words, we are expected to accept the single digit "6" as a "1".  As far as I understand it, this implies that the following is *also* valid:

```xml
    <path d="M280,120 h25 a25,25 0 60 -25,25 z" fill="red"/>
```

And should be parsed identically.


[F.6.2 Out-of-range parameters]: https://www.w3.org/TR/SVG11/single-page.html#implnote-ArcOutOfRangeParameters

**Comment by Ede123** [comment]
Agreed... seems to be one of the stranger decisions in the spec, but in that case lets implement it.

The relevant code is at https://github.com/scour-project/scour/blob/master/scour/svg_regex.py#L250

**Comment by Ede123** [comment]
OK, I'm "confused" by this to say the least...

The relevant section in the SVG 1.1 specification - [8.3.9 The grammar for path data](https://www.w3.org/TR/SVG/paths.html#PathDataBNF) - clearly states a "flag" is supposed to be "0" or "1".

Now if we consider [F.6.2 Out-of-range parameters](https://www.w3.org/TR/SVG11/single-page.html#implnote-ArcOutOfRangeParameters) we should also allow out of range values.

Problem: What do we do with path data like
```SVG
<path d="M280,120 h25 a25,25 0 10 0 -25,25 z" fill="red"/>
```
Now the "large arc flag" would be 10, but properly parsed it's actually 1 and sweep flag would be 0 and the path data therefore corrupted...

Should we consider "out-of-range" parameters to be arbitrarily limited to integers between -9 and 9, i.e. single digits? Or is the SVG spec simply inconsistent here?

**Comment by nthykier** [comment]
Patrick Storz:
> OK, I'm "confused" by this to say the least...
> 
> The relevant section in the SVG 1.1 specification - [8.3.9 The grammar for path data](https://www.w3.org/TR/SVG/paths.html#PathDataBNF) - clearly states a "flag" is supposed to be "0" or "1".
> 
> Now if we consider [F.6.2 Out-of-range parameters](https://www.w3.org/TR/SVG11/single-page.html#implnote-ArcOutOfRangeParameters) we should also allow out of range values.
> 

It is a question of "what you are supposed to generate vs. what you
accept" and parsers are expected to be forgiving according to the spec.


> Problem: What do we do with path data like
> ```SVG
> <path d="M280,120 h25 a25,25 0 10 0 -25,25 z" fill="red"/>
> ```
> Now the "large arc flag" would be 10, but properly parsed it's actually 1 and sweep flag would be 0 and the path data therefore corrupted...
> 

That particular case is well-defined as flag is defined as "1" | "0",
which implies we are only supposed to read a single digit for the flag.

Thus this is read as:

       25,25 0 10 0 -25,25 z
               ^^
        LAF ---/|
                \--- sweep

Which would mean there is a number too much in this case and the syntax
is invalid.

But your concern is still valid for other cases.

> Should we consider "out-of-range" parameters to be arbitrarily limited to integers between -9 and 9, i.e. single digits? Or is the SVG spec simply inconsistent here?
> 

My interpretation would be to read at most one (non-"comma-wsp")
byte/digit for each flag (as the "true" valid flag values are at most
one digit).
  If it is 2-9 we pretend to have read 1.  If it is 0 or 1, then it
follows the standard and is obviously accepted.  If it is "-", we refuse
it as a syntax error.  The reason for rejecting "-" is basically that I
read flags as single byte/digit values.

(Honestly, the spec is ambiguous here but if there are no SVG reference
files with negative values for flags, I would opt for not supporting
them for now - particularly, I am not sure it is worth the extra
complexity if the reference test suite does not include that case)

**Comment by Ede123** [comment]
>  If it is "-", we refuse it as a syntax error. The reason for rejecting "-" is basically that I read flags as single byte/digit values.

There are tests for "negative sweep-flag value" and "negative large-arc-flag value" in https://www.w3.org/Graphics/SVG/Test/20110816/svg/paths-data-20-f.svg, so if our goal is to be able to process the testsuite files without errors, we unfortunately need to handle negative values, too...

**Comment by nthykier** [comment]
Patrick Storz:
>>  If it is "-", we refuse it as a syntax error. The reason for rejecting "-" is basically that I read flags as single byte/digit values.
> 
> There are tests for "negative sweep-flag value" and "negative large-arc-flag value" in https://www.w3.org/Graphics/SVG/Test/20110816/svg/paths-data-20-f.svg, so if our goal is to be able to process the testsuite files without errors, we unfortunately need to handle negative values, too...
> 

On the positive side, it at least clarifies their intention.  But ugh,
it is a lot more complicated ... >.<

**Comment by nthykier** [comment]
That test case appears to _also_ be a test case of [F.5 ‘path’ element implementation notes](https://www.w3.org/TR/SVG11/single-page.html#implnote-PathElementImplementationNotes).  Said section says that any path should be rendered up to (but excluding) the first path command that is in error.  This means that the (invalid) command:

```svg
<path d="M200,200 h-25 a25,2501 025,-25 z" fill="red"/>
```

Should be rendered just as `M200,200 h-25` (and then skipping the `a` and `z` command).  Should scour aggressively optimize the broken path away or should it "ignore" the path (possible with a warning)?
