### ISSUE TITLE
nodeValue.units == Unit.INVALID

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#197]
Prozessiong [File:Happy_new_year_03.svg](https://commons.wikimedia.org/wiki/File:Happy_new_year_03.svg) with default options

> scour -i [Happy_new_year_03.svg](https://upload.wikimedia.org/wikipedia/commons/b/b6/Happy_new_year_03.svg) -o output.svg

leads to following error:

```cmd
Traceback (most recent call last):
  File "C:\Python36\Scripts\scour-script.py", line 11, in <module>
    load_entry_point('scour==0.36', 'console_scripts', 'scour')()
  File "c:\python36\lib\site-packages\scour\scour.py", line 3930, in run
    start(options, input, output)
  File "c:\python36\lib\site-packages\scour\scour.py", line 3898, in start
    out_string = scourString(in_string, options).encode("UTF-8")
  File "c:\python36\lib\site-packages\scour\scour.py", line 3569, in scourString
    _num_attributes_removed += removeDefaultAttributeValues(doc.documentElement, options)
  File "c:\python36\lib\site-packages\scour\scour.py", line 1965, in removeDefaultAttributeValues
    num += removeDefaultAttributeValues(child, options, tainted.copy())
  File "c:\python36\lib\site-packages\scour\scour.py", line 1965, in removeDefaultAttributeValues
    num += removeDefaultAttributeValues(child, options, tainted.copy())
  File "c:\python36\lib\site-packages\scour\scour.py", line 1939, in removeDefaultAttributeValues
    num += removeDefaultAttributeValue(node, attribute)
  File "c:\python36\lib\site-packages\scour\scour.py", line 1911, in removeDefaultAttributeValue
    or ((nodeValue.value == attribute.value) and not (nodeValue.units == Unit.INVALID))):
AttributeError: 'SVGLength' object has no attribute 'units'
```

it seems scour has a problem with [feConvolveMatrix](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feConvolveMatrix) : 
`<feConvolveMatrix divisor="3" kernelMatrix="1 1 1 0 0 0 -1 -1 -1" order="3 3"/>`

----
[min.svg.txt](https://github.com/scour-project/scour/files/2088030/min.svg.txt)
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg height="1059.79" width="3109.05" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <filter id="a" color-interpolation-filters="sRGB" height="1.5" width="1.5" x="-.25" y="-.25">
  <feConvolveMatrix divisor="3" kernelMatrix="1 1 1 0 0 0 -1 -1 -1" order="3 3"/>
 </filter>
 <path d="m-302.503 345.932h-102.493v99.999h-22.507v-210h22.507v87.502h102.493v-87.501h22.507v209.998h-22.507zm57.365-25.002v-22.498h80.002q42.496 0 42.496 42.503v62.5q0 42.496-42.496 42.496h-50.003q-42.496 0-42.496-42.496v-.503q0-42 42.496-42h55v22.499h-55q-19.997 0-19.997 19.5v.504q0 19.997 19.997 19.997h50.003q19.997 0 19.997-19.997v-62.5q0-20.004-19.997-20.004zm170.22 162.507h-22.507v-142.502q0-42.503 42.504-42.503h50.003q42.495 0 42.495 42.503v62.5q0 42.496-42.495 42.496h-55v-22.5h55q19.996 0 19.996-19.996v-62.5q0-20.004-19.996-20.004h-50.003q-19.997 0-19.997 20.004zm160.156 0h-22.507v-142.502q0-42.503 42.504-42.503h50.003q42.495 0 42.495 42.503v62.5q0 42.496-42.495 42.496h-55v-22.5h55q19.996 0 19.996-19.996v-62.5q0-20.004-19.996-20.004h-50.003q-19.997 0-19.997 20.004zm137.65-185.005h22.506v105.003q0 19.997 19.997 19.997h70v-125h22.499v154.998q0 42.503-42.496 42.503h-55v-22.5h55q19.997 0 19.997-20.003v-7.5h-70q-42.504 0-42.504-42.496zm245.162-21.5v168.999h-22.506v-210h20.004l117.5 170.503v-170.502h22.5v209.998h-20.005zm285.058 146.5v22.499h-80.002q-42.504 0-42.504-42.496v-62.5q0-42.503 42.504-42.503h50.003q42.496 0 42.496 42.503v.496q0 42-42.496 42h-55v-22.5h55q19.997 0 19.997-19.5v-.496q0-20.004-19.997-20.004h-50.003q-19.997 0-19.997 20.004v62.5q0 19.997 19.997 19.997zm198.463 22.498h-20.248l-40.505-111.999-39.001 112h-20.249l-54.245-147.5h23.75l40.246 112.504 39.505-112.503h19.996l40.253 112.503 39.497-112.503h23.75zm199.982-100.745-83.253-109.253h28.251l66.247 89.004 66.001-89.004h28.252l-83 109.253v100.745h-22.5zm240.715 78.247v22.499h-80.002q-42.503 0-42.503-42.496v-62.5q0-42.503 42.503-42.503h50.003q42.496 0 42.496 42.503v.496q0 42-42.496 42h-55v-22.5h55q19.997 0 19.997-19.5v-.496q0-20.004-19.997-20.004h-50.003q-19.997 0-19.997 20.004v62.5q0 19.997 19.997 19.997zm45.212-102.502v-22.498h80.001q42.496 0 42.496 42.503v62.5q0 42.496-42.496 42.496h-50.003q-42.495 0-42.495-42.496v-.503q0-42 42.495-42h55v22.499h-55q-19.996 0-19.996 19.5v.504q0 19.997 19.996 19.997h50.003q19.997 0 19.997-19.997v-62.5q0-20.004-19.997-20.004zm170.219 125h-22.507v-104.994q0-42.503 42.504-42.503h17.501v22.499h-17.501q-19.997 0-19.997 20.004z" fill="#f00" filter="url(#a)"/>
</svg>
```
![min](https://user-images.githubusercontent.com/15687581/41203751-b8c92f12-6cdb-11e8-9227-7183040f3c0d.png)

**Comment by Ede123** [comment]
Same issue as #189 which has been fixed by #192.
