### ISSUE TITLE
Scour as a library

### ISSUE THREAD

**Issue by hummeleBop** [scour-project/scour#269]
Hello there,

For some reasons, I'm using Scour as a library.
It works almost as expected, but I get an error with the following code :

``` python
import sys
from scour.svg_regex import SVGPathParser
from scour.scour import sanitizeOptions, serializePath

#path2d = "\n".join(sys.stdin.readlines())
path2d = 'M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z'
pathData = SVGPathParser().parse(path2d)
options = sanitizeOptions()
print(serializePath(pathData,options))
```
```
Traceback (most recent call last):
  File "C:\dev\projects\Woolf\tools\vanillapath2d\vanillapath2d.py", line 29, in <module>
    print(serializePath(pathData,options))
  File "C:\programs\python3\lib\site-packages\scour-0.38.2-py3.9.egg\scour\scour.py", line 2898, in serializePath
  File "C:\programs\python3\lib\site-packages\scour-0.38.2-py3.9.egg\scour\scour.py", line 2898, in <genexpr>
  File "C:\programs\python3\lib\site-packages\scour-0.38.2-py3.9.egg\scour\scour.py", line 2926, in scourCoordinates
  File "C:\programs\python3\lib\site-packages\scour-0.38.2-py3.9.egg\scour\scour.py", line 2989, in scourUnitlessLength
NameError: name 'scouringContext' is not defined
```

Perhaps we should be able to change the value of scouringContext from the outside world.
The ability to use scour from another code could be really useful.

Thanks a lot,
Regards

**Comment by hummeleBop** [comment]
Oh that was easy,

I managed to get this working like this 👍 
``` python
#import sys
from decimal import Context
from xml.dom.minidom import getDOMImplementation
from scour import svg_regex
from scour import scour

scour.scouringContext = Context(prec=5) # digits
scour.scouringContextC = Context(prec=5) # cdigits

scour._num_bytes_saved_in_path_data = 0
scour._num_path_segments_removed = 0

#path2d = "\n".join(sys.stdin.readlines())
path2d = 'M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z'

impl = getDOMImplementation()
dt = impl.createDocumentType('svg', '-//W3C//DTD SVG 1.1//EN', 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd')
doc = impl.createDocument('http://www.w3.org/2000/svg', 'svg', dt)

svg = doc.documentElement
svg.setAttribute('xmlns', 'http://www.w3.org/2000/svg')
svg.setAttribute('version', '1.1')
svg.setAttribute('xmlns:xlink', 'http://www.w3.org/1999/xlink')
node = doc.createElement('path')
node.setAttribute('d', path2d)
svg.appendChild(node)

options = scour.sanitizeOptions()
scour.cleanPath(node, options)

print(node.getAttribute('d'))

pathData = svg_regex.SVGPathParser().parse(node.getAttribute('d'))
print(scour.serializePath(pathData,options))
```

The fact scour is available as a library is really helpful

**Comment by Ede123** [comment]
Great to hear you could solve your issue!

It's true that nobody thought about making individual optimization functions of scour available to other tools.

There are some plans to come up with a stable public API (see #119 and #121), however this API would still not expose the function you wanted to use, so we might to have to think about this in more detail.
