### ISSUE TITLE
Expecting a nonnegative number in path

### ISSUE THREAD

**Issue by IceflowRE** [scour-project/scour#279]
Iam not sure if Inkscape creates invalid svgs or what exactly happened.

```svg
<svg version="1.1" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#"
     xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <path id="path958-2-7-5-5-7-5-9-3" style="color:#000000;fill:#ffffff;stroke-linecap:round" d="m 752,472 a -40,40 0 0 1 40,40 -40,40 0 0 1 -40,40 h -26.94922 a -120,120 0 0 0 6.9492,-40 -120,120 0 0 0 -6.9492,-40 z m -253.12502,0 a -120,120 0 0 0 -6.875,40 -120,120 0 0 0 6.9492,40 h -226.9492 a -40,40 0 0 1 -40,-40 -40,40 0 0 1 40,-40 z"/>
</svg>
```
log
```
  File "symbconv\export.py", line 32, in optimize_svg
    scour.start(options, in_file, out_file)
  File "scour\scour.py", line 4152, in start
    out_string = scourString(in_string, options, stats=stats).encode("UTF-8")
  File "scour\scour.py", line 3805, in scourString
    clean_path(elem, options, stats)
  File "scour\scour.py", line 2282, in clean_path
    path = svg_parser.parse(oldPathStr)
  File "scour\svg_regex.py", line 160, in parse
    return self.rule_svg_path(next_val_fn, token)
  File "scour\svg_regex.py", line 168, in rule_svg_path
    command_group, token = rule(next_val_fn, token)
  File "scour\svg_regex.py", line 235, in rule_elliptical_arc
    raise SyntaxError("expecting a nonnegative number; got %r" % (token,))
SyntaxError: expecting a nonnegative number; got ('float', '-40')
```

**Comment by ernstki** [comment]
Inkscape 1.1.2 and scour 0.37 on macOS:

<details>
<summary><code>expecting a nonnegative number</code> traceback</summary>
<p><pre><code>Traceback (most recent call last):
  File "output_scour.py", line 72, in <module>
    ScourInkscape().run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 156, in save_raw
    self.save(self.options.output)
  File "output_scour.py", line 69, in save
    stream.write(scourString(self.svg.tostring(), self.options).encode('utf8'))
  File "/Applications/Inkscape.app/Contents/Resources/lib/python3.8/site-packages/scour/scour.py", line 3601, in scourString
    cleanPath(elem, options)
  File "/Applications/Inkscape.app/Contents/Resources/lib/python3.8/site-packages/scour/scour.py", line 2070, in cleanPath
    path = svg_parser.parse(oldPathStr)
  File "/Applications/Inkscape.app/Contents/Resources/lib/python3.8/site-packages/scour/svg_regex.py", line 160, in parse
    return self.rule_svg_path(next_val_fn, token)
  File "/Applications/Inkscape.app/Contents/Resources/lib/python3.8/site-packages/scour/svg_regex.py", line 168, in rule_svg_path
    command_group, token = rule(next_val_fn, token)
  File "/Applications/Inkscape.app/Contents/Resources/lib/python3.8/site-packages/scour/svg_regex.py", line 235, in rule_elliptical_arc
    raise SyntaxError("expecting a nonnegative number; got %r" % (token,))
SyntaxError: expecting a nonnegative number; got ('float', '-9')
</code></pre></p>
</details>  

<details>
<summary>the offending SVG</summary>
<p><pre><code>&lt;?xml version="1.0" encoding="UTF-8" standalone="no"?&gt;
&lt;svg
   viewBox=&quot;0 0 21 18&quot;
   version=&quot;1.1&quot;
   id=&quot;svg826&quot;
   sodipodi:docname=&quot;ff-rewind-15.svg&quot;
   width=&quot;21&quot;
   height=&quot;18&quot;
   inkscape:version=&quot;1.1.2 (b8e25be8, 2022-02-05)&quot;
   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
   xmlns=&quot;http://www.w3.org/2000/svg&quot;
   xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;&gt;
  &lt;defs
     id=&quot;defs830&quot; /&gt;
  &lt;sodipodi:namedview
     id=&quot;namedview828&quot;
     pagecolor=&quot;#ffffff&quot;
     bordercolor=&quot;#999999&quot;
     borderopacity=&quot;1&quot;
     inkscape:pageshadow=&quot;0&quot;
     inkscape:pageopacity=&quot;0&quot;
     inkscape:pagecheckerboard=&quot;0&quot;
     showgrid=&quot;false&quot;
     inkscape:zoom=&quot;45.254834&quot;
     inkscape:cx=&quot;10.551359&quot;
     inkscape:cy=&quot;8.8388348&quot;
     inkscape:window-width=&quot;1920&quot;
     inkscape:window-height=&quot;1027&quot;
     inkscape:window-x=&quot;0&quot;
     inkscape:window-y=&quot;25&quot;
     inkscape:window-maximized=&quot;0&quot;
     inkscape:current-layer=&quot;svg826&quot;
     fit-margin-top=&quot;0&quot;
     fit-margin-left=&quot;0&quot;
     fit-margin-right=&quot;0&quot;
     fit-margin-bottom=&quot;0&quot;
     showguides=&quot;true&quot;
     inkscape:guide-bbox=&quot;true&quot;
     inkscape:snap-center=&quot;true&quot;
     inkscape:snap-object-midpoints=&quot;true&quot;&gt;
    &lt;sodipodi:guide
       position=&quot;9,18&quot;
       orientation=&quot;1,0&quot;
       id=&quot;guide910&quot; /&gt;
    &lt;sodipodi:guide
       position=&quot;2.9999999,9&quot;
       orientation=&quot;0,-1&quot;
       id=&quot;guide912&quot; /&gt;
  &lt;/sodipodi:namedview&gt;
  &lt;path
     d=&quot;m 9,0 a -9,9 0 0 1 9,9 h 3 l -4,4 -4,-4 h 3 A -7,7 0 0 0 9,2 -7,7 0 0 0 2,9 -7,7 0 0 0 9,16 c 1.5,0 2.91,-0.5 4.06,-1.3 l 1.44,1.44 C 12.96,17.3 11.06,18 9,18 A -9,9 0 0 1 0,9 -9,9 0 0 1 9,0&quot;
     id=&quot;path824&quot; /&gt;
  &lt;text
     xml:space=&quot;preserve&quot;
     style=&quot;font-style:normal;font-weight:normal;font-size:8px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.999969&quot;
     x=&quot;5.0998874&quot;
     y=&quot;11.613003&quot;
     id=&quot;text11458&quot;
     transform=&quot;scale(0.99996911,1.0000309)&quot;&gt;&lt;tspan
       sodipodi:role=&quot;line&quot;
       id=&quot;tspan11456&quot;
       x=&quot;5.0998874&quot;
       y=&quot;11.613003&quot;
       style=&quot;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:8px;font-family:&#39;SF Compact Display&#39;;-inkscape-font-specification:&#39;SF Compact Display, Normal&#39;;font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;stroke-width:0.999969&quot;&gt;15&lt;/tspan&gt;&lt;/text&gt;
&lt;/svg&gt;
</code></pre></p>
</details>

<details>
<summary>using these settings in the GUI dialog box</summary>
<p><br><img width="1315" alt="Image" src="https://github.com/user-attachments/assets/1981025a-5f83-4201-8f85-e272e2574a13" /></p>
</details>  

I'll try the same SVG with the latest version of scour, and the latest version of Inkscape for macOS and report back.

**Edit:** same result with scour v0.38.2 and 0609c59 (latest master) using this command line, which should roughly correspond to the settings used above

```console
$ scour --set-precision=5 --create-groups --renderer-workaround --strip-xml-prolog --remove-metadata --enable-comment-stripping --enable-viewboxing --enable-id-stripping --shorten-ids --protect-ids-noninkscape path/to/ff-rewind-15.svg ff-rewind-15.optim.svg
Traceback (most recent call last):
  File "/Users/me/.local/bin/scour", line 8, in <module>
    sys.exit(run())
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/scour.py", line 4220, in run
    start(options, input, output)
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/scour.py", line 4188, in start
    out_string = scourString(in_string, options).encode("UTF-8")
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/scour.py", line 3842, in scourString
    cleanPath(elem, options)
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/scour.py", line 2289, in cleanPath
    path = svg_parser.parse(oldPathStr)
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/svg_regex.py", line 160, in parse
    return self.rule_svg_path(next_val_fn, token)
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/svg_regex.py", line 168, in rule_svg_path
    command_group, token = rule(next_val_fn, token)
  File "/Users/me/.local/pipx/venvs/scour/lib/python3.8/site-packages/scour/svg_regex.py", line 235, in rule_elliptical_arc
    raise SyntaxError("expecting a nonnegative number; got %r" % (token,))
SyntaxError: expecting a nonnegative number; got ('float', '-9')
```

Leaving off all the command-line options (or unchecking all the GUI options, which, yes, I know, _enables_ some non-default command-line switches under the hood) doesn't seem to affect the error state.

Same result with Inkscape 1.4.2 (ebf0e940, 2025-05-08), which bundles scour 0.38.2.

### See also

* https://bugs.launchpad.net/inkscape/+bug/638764

**Comment by ernstki** [comment]
As I read it, the SVG 1.1 (Second Edition) standard [says](https://www.w3.org/TR/SVG11/implnote.html#ArcOutOfRangeParameters) that negative values should be acceptable here:

> F.6 Elliptical arc implementation notes
>
> If r<sub>x</sub> or r<sub>y</sub> have negative signs, these are dropped; the absolute value is used instead.

This condition arises with Inkscapes 1.1.x (and possibly older), when you mirror a path; horizontally, in my case. The diff below shows the Inkscape SVG output for v1.1.2 compared to v1.4.2, where the extraneous minus sign from the ellipse radii appears to have been dropped.

```diff
--- 1.mirrored.svg	2025-05-27 08:15:31
+++ 1.mirrored-1.4.2.svg	2025-05-27 08:25:08
@@ -3,8 +3,8 @@
    version="1.1"
    viewBox="0 0 21 18"
    id="svg1"
-   sodipodi:docname="1.mirrored.svg"
-   inkscape:version="1.1.2 (b8e25be8, 2022-02-05)"
+   sodipodi:docname="1.mirrored-1.4.2.svg"
+   inkscape:version="1.4.2 (ebf0e940, 2025-05-08)"
    xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
    xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
    xmlns="http://www.w3.org/2000/svg"
@@ -32,6 +32,6 @@
      inkscape:current-layer="svg1"
      inkscape:pageshadow="0" />
   <path
-     d="m 9,0 a -9,9 0 0 1 9,9 h 3 l -4,4 -4,-4 h 3 A -7,7 0 0 0 9,2 -7,7 0 0 0 2,9 -7,7 0 0 0 9,16 c 1.5,0 2.91,-0.5 4.06,-1.3 l 1.44,1.44 C 12.96,17.3 11.06,18 9,18 A -9,9 0 0 1 0,9 -9,9 0 0 1 9,0"
+     d="m 9,0 a 9,9 0 0 1 9,9 h 3 l -4,4 -4,-4 h 3 A 7,7 0 0 0 9,2 7,7 0 0 0 2,9 7,7 0 0 0 9,16 c 1.5,0 2.91,-0.5 4.06,-1.3 l 1.44,1.44 C 12.96,17.3 11.06,18 9,18 A 9,9 0 0 1 0,9 9,9 0 0 1 9,0"
      id="path1" />
 </svg>
```

For now, you can effectively work around this problem removing the minus signs for first two coordinates — the rx and ry — for any `a` or `A` elements using the Inkscape XML editor, or a text editor. That will be somewhat unpleasant for complex documents, though, unless you are good with sed or Perl.

Re-saving a document with a newer Inkscape does not appear to correct the negative radii. So those documents created with Inkscape 1.x _will_ continue to exist in the wild, and they appear to be valid according to the standard.

If the maintainers (@oberstet and @Ede123, I think, currently?) believe this is worth fixing in scour, I can do a PR for this.
